### ISSUE TITLE
Improve: Configuración de parámetros

### ISSUE THREAD

**Issue by diegodi** [niclabs/moca-ballot-selection#2]
Incluir algún menú de administrador que permita subir el archivo de llave pública y la lista de candidatos en lugar de pasarlas manualmente a las carpetas del código.

**Comment by camilog** [comment]
La idea aca es configurar la tablet a través de códigos QR que posean la información de la lista de candidatos y la llave pública

**Comment by diegodi** [comment]
Lectura de ambos códigos QR se realiza con éxito, ambos archivos se guardan internamente en la aplicación. Lectura de llave pública al momento de generar voto encriptado falla.

**Comment by diegodi** [comment]
Solucionado y funcionando.
